### ISSUE TITLE
False pw found

### ISSUE THREAD

**Issue by hitem** [thenurhabib/wphunter#1]
Hello,
I notice you have the exact same script as this: https://github.com/guelfoweb/wpbrute
However, when running yours i always come up with wrong passwords when testing on my testsystem. Is it possible to add additional checks to the "$REQ" == "" ? (timeouts etc).

Thanks.

**Comment by hitem** [comment]
I resolved this stolen code myself. ty

**Comment by sovetski** [comment]
@hitem great, but why you don't share the solution you found?...
